[package]
name = "wasm-viewer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
js-sys = "0.3.61"
wasm-bindgen = "0.2.84"
wasmparser = "0.104.0"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
